package dao.mapper;

import dao.model.BookInfo;
import dao.model.BookInfoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BookInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo_
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    int countByExample(BookInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo_
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    int deleteByExample(BookInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo_
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    int deleteByPrimaryKey(String isbn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo_
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    int insert(BookInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo_
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    int insertSelective(BookInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo_
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    List<BookInfo> selectByExample(BookInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo_
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    BookInfo selectByPrimaryKey(String isbn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo_
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    int updateByExampleSelective(@Param("record") BookInfo record, @Param("example") BookInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo_
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    int updateByExample(@Param("record") BookInfo record, @Param("example") BookInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo_
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    int updateByPrimaryKeySelective(BookInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo_
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    int updateByPrimaryKey(BookInfo record);
}