package dao.mapper;

import java.util.List;

import dao.model.OrderInfo;
import dao.model.OrderInfoExample;
import dao.model.OrderInfoKey;
import org.apache.ibatis.annotations.Param;

public interface OrderInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo_
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    int countByExample(OrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo_
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    int deleteByExample(OrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo_
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    int deleteByPrimaryKey(OrderInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo_
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    int insert(OrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo_
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    int insertSelective(OrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo_
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    List<OrderInfo> selectByExample(OrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo_
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    OrderInfo selectByPrimaryKey(OrderInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo_
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    int updateByExampleSelective(@Param("record") OrderInfo record, @Param("example") OrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo_
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    int updateByExample(@Param("record") OrderInfo record, @Param("example") OrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo_
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    int updateByPrimaryKeySelective(OrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo_
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    int updateByPrimaryKey(OrderInfo record);
}