package dao.model;

import java.util.Date;

public class FeedBackInfo extends FeedBackInfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedbackinfo_.datetime
     *
     * @mbggenerated Fri Dec 29 19:57:10 CST 2017
     */
    private Date datetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedbackinfo_.context
     *
     * @mbggenerated Fri Dec 29 19:57:10 CST 2017
     */
    private String context;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedbackinfo_.datetime
     *
     * @return the value of feedbackinfo_.datetime
     *
     * @mbggenerated Fri Dec 29 19:57:10 CST 2017
     */
    public Date getDatetime() {
        return datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedbackinfo_.datetime
     *
     * @param datetime the value for feedbackinfo_.datetime
     *
     * @mbggenerated Fri Dec 29 19:57:10 CST 2017
     */
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedbackinfo_.context
     *
     * @return the value of feedbackinfo_.context
     *
     * @mbggenerated Fri Dec 29 19:57:10 CST 2017
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedbackinfo_.context
     *
     * @param context the value for feedbackinfo_.context
     *
     * @mbggenerated Fri Dec 29 19:57:10 CST 2017
     */
    public void setContext(String context) {
        this.context = context == null ? null : context.trim();
    }
}