package dao.model;

import java.util.Date;

public class MarketInfo extends MarketInfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column marketinfo_.datetime
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    private Date datetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column marketinfo_.quantity
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    private Integer quantity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column marketinfo_.datetime
     *
     * @return the value of marketinfo_.datetime
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    public Date getDatetime() {
        return datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column marketinfo_.datetime
     *
     * @param datetime the value for marketinfo_.datetime
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column marketinfo_.quantity
     *
     * @return the value of marketinfo_.quantity
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column marketinfo_.quantity
     *
     * @param quantity the value for marketinfo_.quantity
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
}