package dao.model;

import java.util.Date;

public class OrderInfo extends OrderInfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo_.quantity
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo_.markinfo
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    private String markinfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo_.datetime
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    private Date datetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo_.orderstate
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    private Integer orderstate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo_.quantity
     *
     * @return the value of orderinfo_.quantity
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo_.quantity
     *
     * @param quantity the value for orderinfo_.quantity
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo_.markinfo
     *
     * @return the value of orderinfo_.markinfo
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    public String getMarkinfo() {
        return markinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo_.markinfo
     *
     * @param markinfo the value for orderinfo_.markinfo
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    public void setMarkinfo(String markinfo) {
        this.markinfo = markinfo == null ? null : markinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo_.datetime
     *
     * @return the value of orderinfo_.datetime
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    public Date getDatetime() {
        return datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo_.datetime
     *
     * @param datetime the value for orderinfo_.datetime
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo_.orderstate
     *
     * @return the value of orderinfo_.orderstate
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    public Integer getOrderstate() {
        return orderstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo_.orderstate
     *
     * @param orderstate the value for orderinfo_.orderstate
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    public void setOrderstate(Integer orderstate) {
        this.orderstate = orderstate;
    }
}