package dao.mapper;

import java.util.List;

import dao.model.UserInfo;
import dao.model.UserInfoExample;
import org.apache.ibatis.annotations.Param;

public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo_
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    int countByExample(UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo_
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    int deleteByExample(UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo_
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo_
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo_
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    int insertSelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo_
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    List<UserInfo> selectByExample(UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo_
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    UserInfo selectByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo_
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    int updateByExampleSelective(@Param("record") UserInfo record, @Param("example") UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo_
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    int updateByExample(@Param("record") UserInfo record, @Param("example") UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo_
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    int updateByPrimaryKeySelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo_
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    int updateByPrimaryKey(UserInfo record);
}