package dao.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BookInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bookinfo_
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bookinfo_
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bookinfo_
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo_
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    public BookInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo_
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo_
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo_
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo_
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo_
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo_
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo_
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo_
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo_
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo_
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bookinfo_
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIsbnIsNull() {
            addCriterion("ISBN is null");
            return (Criteria) this;
        }

        public Criteria andIsbnIsNotNull() {
            addCriterion("ISBN is not null");
            return (Criteria) this;
        }

        public Criteria andIsbnEqualTo(String value) {
            addCriterion("ISBN =", value, "isbn");
            return (Criteria) this;
        }

        public Criteria andIsbnNotEqualTo(String value) {
            addCriterion("ISBN <>", value, "isbn");
            return (Criteria) this;
        }

        public Criteria andIsbnGreaterThan(String value) {
            addCriterion("ISBN >", value, "isbn");
            return (Criteria) this;
        }

        public Criteria andIsbnGreaterThanOrEqualTo(String value) {
            addCriterion("ISBN >=", value, "isbn");
            return (Criteria) this;
        }

        public Criteria andIsbnLessThan(String value) {
            addCriterion("ISBN <", value, "isbn");
            return (Criteria) this;
        }

        public Criteria andIsbnLessThanOrEqualTo(String value) {
            addCriterion("ISBN <=", value, "isbn");
            return (Criteria) this;
        }

        public Criteria andIsbnLike(String value) {
            addCriterion("ISBN like", value, "isbn");
            return (Criteria) this;
        }

        public Criteria andIsbnNotLike(String value) {
            addCriterion("ISBN not like", value, "isbn");
            return (Criteria) this;
        }

        public Criteria andIsbnIn(List<String> values) {
            addCriterion("ISBN in", values, "isbn");
            return (Criteria) this;
        }

        public Criteria andIsbnNotIn(List<String> values) {
            addCriterion("ISBN not in", values, "isbn");
            return (Criteria) this;
        }

        public Criteria andIsbnBetween(String value1, String value2) {
            addCriterion("ISBN between", value1, value2, "isbn");
            return (Criteria) this;
        }

        public Criteria andIsbnNotBetween(String value1, String value2) {
            addCriterion("ISBN not between", value1, value2, "isbn");
            return (Criteria) this;
        }

        public Criteria andBooknameIsNull() {
            addCriterion("bookname is null");
            return (Criteria) this;
        }

        public Criteria andBooknameIsNotNull() {
            addCriterion("bookname is not null");
            return (Criteria) this;
        }

        public Criteria andBooknameEqualTo(String value) {
            addCriterion("bookname =", value, "bookname");
            return (Criteria) this;
        }

        public Criteria andBooknameNotEqualTo(String value) {
            addCriterion("bookname <>", value, "bookname");
            return (Criteria) this;
        }

        public Criteria andBooknameGreaterThan(String value) {
            addCriterion("bookname >", value, "bookname");
            return (Criteria) this;
        }

        public Criteria andBooknameGreaterThanOrEqualTo(String value) {
            addCriterion("bookname >=", value, "bookname");
            return (Criteria) this;
        }

        public Criteria andBooknameLessThan(String value) {
            addCriterion("bookname <", value, "bookname");
            return (Criteria) this;
        }

        public Criteria andBooknameLessThanOrEqualTo(String value) {
            addCriterion("bookname <=", value, "bookname");
            return (Criteria) this;
        }

        public Criteria andBooknameLike(String value) {
            addCriterion("bookname like", value, "bookname");
            return (Criteria) this;
        }

        public Criteria andBooknameNotLike(String value) {
            addCriterion("bookname not like", value, "bookname");
            return (Criteria) this;
        }

        public Criteria andBooknameIn(List<String> values) {
            addCriterion("bookname in", values, "bookname");
            return (Criteria) this;
        }

        public Criteria andBooknameNotIn(List<String> values) {
            addCriterion("bookname not in", values, "bookname");
            return (Criteria) this;
        }

        public Criteria andBooknameBetween(String value1, String value2) {
            addCriterion("bookname between", value1, value2, "bookname");
            return (Criteria) this;
        }

        public Criteria andBooknameNotBetween(String value1, String value2) {
            addCriterion("bookname not between", value1, value2, "bookname");
            return (Criteria) this;
        }

        public Criteria andAuthorIsNull() {
            addCriterion("author is null");
            return (Criteria) this;
        }

        public Criteria andAuthorIsNotNull() {
            addCriterion("author is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorEqualTo(String value) {
            addCriterion("author =", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotEqualTo(String value) {
            addCriterion("author <>", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorGreaterThan(String value) {
            addCriterion("author >", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorGreaterThanOrEqualTo(String value) {
            addCriterion("author >=", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorLessThan(String value) {
            addCriterion("author <", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorLessThanOrEqualTo(String value) {
            addCriterion("author <=", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorLike(String value) {
            addCriterion("author like", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotLike(String value) {
            addCriterion("author not like", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorIn(List<String> values) {
            addCriterion("author in", values, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotIn(List<String> values) {
            addCriterion("author not in", values, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorBetween(String value1, String value2) {
            addCriterion("author between", value1, value2, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotBetween(String value1, String value2) {
            addCriterion("author not between", value1, value2, "author");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(Float value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(Float value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(Float value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(Float value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(Float value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(Float value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<Float> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<Float> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(Float value1, Float value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(Float value1, Float value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andDiscountIsNull() {
            addCriterion("discount is null");
            return (Criteria) this;
        }

        public Criteria andDiscountIsNotNull() {
            addCriterion("discount is not null");
            return (Criteria) this;
        }

        public Criteria andDiscountEqualTo(Float value) {
            addCriterion("discount =", value, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountNotEqualTo(Float value) {
            addCriterion("discount <>", value, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountGreaterThan(Float value) {
            addCriterion("discount >", value, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountGreaterThanOrEqualTo(Float value) {
            addCriterion("discount >=", value, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountLessThan(Float value) {
            addCriterion("discount <", value, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountLessThanOrEqualTo(Float value) {
            addCriterion("discount <=", value, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountIn(List<Float> values) {
            addCriterion("discount in", values, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountNotIn(List<Float> values) {
            addCriterion("discount not in", values, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountBetween(Float value1, Float value2) {
            addCriterion("discount between", value1, value2, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountNotBetween(Float value1, Float value2) {
            addCriterion("discount not between", value1, value2, "discount");
            return (Criteria) this;
        }

        public Criteria andRemainnumIsNull() {
            addCriterion("remainnum is null");
            return (Criteria) this;
        }

        public Criteria andRemainnumIsNotNull() {
            addCriterion("remainnum is not null");
            return (Criteria) this;
        }

        public Criteria andRemainnumEqualTo(Integer value) {
            addCriterion("remainnum =", value, "remainnum");
            return (Criteria) this;
        }

        public Criteria andRemainnumNotEqualTo(Integer value) {
            addCriterion("remainnum <>", value, "remainnum");
            return (Criteria) this;
        }

        public Criteria andRemainnumGreaterThan(Integer value) {
            addCriterion("remainnum >", value, "remainnum");
            return (Criteria) this;
        }

        public Criteria andRemainnumGreaterThanOrEqualTo(Integer value) {
            addCriterion("remainnum >=", value, "remainnum");
            return (Criteria) this;
        }

        public Criteria andRemainnumLessThan(Integer value) {
            addCriterion("remainnum <", value, "remainnum");
            return (Criteria) this;
        }

        public Criteria andRemainnumLessThanOrEqualTo(Integer value) {
            addCriterion("remainnum <=", value, "remainnum");
            return (Criteria) this;
        }

        public Criteria andRemainnumIn(List<Integer> values) {
            addCriterion("remainnum in", values, "remainnum");
            return (Criteria) this;
        }

        public Criteria andRemainnumNotIn(List<Integer> values) {
            addCriterion("remainnum not in", values, "remainnum");
            return (Criteria) this;
        }

        public Criteria andRemainnumBetween(Integer value1, Integer value2) {
            addCriterion("remainnum between", value1, value2, "remainnum");
            return (Criteria) this;
        }

        public Criteria andRemainnumNotBetween(Integer value1, Integer value2) {
            addCriterion("remainnum not between", value1, value2, "remainnum");
            return (Criteria) this;
        }

        public Criteria andSoldnumIsNull() {
            addCriterion("soldnum is null");
            return (Criteria) this;
        }

        public Criteria andSoldnumIsNotNull() {
            addCriterion("soldnum is not null");
            return (Criteria) this;
        }

        public Criteria andSoldnumEqualTo(Integer value) {
            addCriterion("soldnum =", value, "soldnum");
            return (Criteria) this;
        }

        public Criteria andSoldnumNotEqualTo(Integer value) {
            addCriterion("soldnum <>", value, "soldnum");
            return (Criteria) this;
        }

        public Criteria andSoldnumGreaterThan(Integer value) {
            addCriterion("soldnum >", value, "soldnum");
            return (Criteria) this;
        }

        public Criteria andSoldnumGreaterThanOrEqualTo(Integer value) {
            addCriterion("soldnum >=", value, "soldnum");
            return (Criteria) this;
        }

        public Criteria andSoldnumLessThan(Integer value) {
            addCriterion("soldnum <", value, "soldnum");
            return (Criteria) this;
        }

        public Criteria andSoldnumLessThanOrEqualTo(Integer value) {
            addCriterion("soldnum <=", value, "soldnum");
            return (Criteria) this;
        }

        public Criteria andSoldnumIn(List<Integer> values) {
            addCriterion("soldnum in", values, "soldnum");
            return (Criteria) this;
        }

        public Criteria andSoldnumNotIn(List<Integer> values) {
            addCriterion("soldnum not in", values, "soldnum");
            return (Criteria) this;
        }

        public Criteria andSoldnumBetween(Integer value1, Integer value2) {
            addCriterion("soldnum between", value1, value2, "soldnum");
            return (Criteria) this;
        }

        public Criteria andSoldnumNotBetween(Integer value1, Integer value2) {
            addCriterion("soldnum not between", value1, value2, "soldnum");
            return (Criteria) this;
        }

        public Criteria andDiscribeIsNull() {
            addCriterion("discribe is null");
            return (Criteria) this;
        }

        public Criteria andDiscribeIsNotNull() {
            addCriterion("discribe is not null");
            return (Criteria) this;
        }

        public Criteria andDiscribeEqualTo(String value) {
            addCriterion("discribe =", value, "discribe");
            return (Criteria) this;
        }

        public Criteria andDiscribeNotEqualTo(String value) {
            addCriterion("discribe <>", value, "discribe");
            return (Criteria) this;
        }

        public Criteria andDiscribeGreaterThan(String value) {
            addCriterion("discribe >", value, "discribe");
            return (Criteria) this;
        }

        public Criteria andDiscribeGreaterThanOrEqualTo(String value) {
            addCriterion("discribe >=", value, "discribe");
            return (Criteria) this;
        }

        public Criteria andDiscribeLessThan(String value) {
            addCriterion("discribe <", value, "discribe");
            return (Criteria) this;
        }

        public Criteria andDiscribeLessThanOrEqualTo(String value) {
            addCriterion("discribe <=", value, "discribe");
            return (Criteria) this;
        }

        public Criteria andDiscribeLike(String value) {
            addCriterion("discribe like", value, "discribe");
            return (Criteria) this;
        }

        public Criteria andDiscribeNotLike(String value) {
            addCriterion("discribe not like", value, "discribe");
            return (Criteria) this;
        }

        public Criteria andDiscribeIn(List<String> values) {
            addCriterion("discribe in", values, "discribe");
            return (Criteria) this;
        }

        public Criteria andDiscribeNotIn(List<String> values) {
            addCriterion("discribe not in", values, "discribe");
            return (Criteria) this;
        }

        public Criteria andDiscribeBetween(String value1, String value2) {
            addCriterion("discribe between", value1, value2, "discribe");
            return (Criteria) this;
        }

        public Criteria andDiscribeNotBetween(String value1, String value2) {
            addCriterion("discribe not between", value1, value2, "discribe");
            return (Criteria) this;
        }

        public Criteria andShelftimeIsNull() {
            addCriterion("shelftime is null");
            return (Criteria) this;
        }

        public Criteria andShelftimeIsNotNull() {
            addCriterion("shelftime is not null");
            return (Criteria) this;
        }

        public Criteria andShelftimeEqualTo(Date value) {
            addCriterion("shelftime =", value, "shelftime");
            return (Criteria) this;
        }

        public Criteria andShelftimeNotEqualTo(Date value) {
            addCriterion("shelftime <>", value, "shelftime");
            return (Criteria) this;
        }

        public Criteria andShelftimeGreaterThan(Date value) {
            addCriterion("shelftime >", value, "shelftime");
            return (Criteria) this;
        }

        public Criteria andShelftimeGreaterThanOrEqualTo(Date value) {
            addCriterion("shelftime >=", value, "shelftime");
            return (Criteria) this;
        }

        public Criteria andShelftimeLessThan(Date value) {
            addCriterion("shelftime <", value, "shelftime");
            return (Criteria) this;
        }

        public Criteria andShelftimeLessThanOrEqualTo(Date value) {
            addCriterion("shelftime <=", value, "shelftime");
            return (Criteria) this;
        }

        public Criteria andShelftimeIn(List<Date> values) {
            addCriterion("shelftime in", values, "shelftime");
            return (Criteria) this;
        }

        public Criteria andShelftimeNotIn(List<Date> values) {
            addCriterion("shelftime not in", values, "shelftime");
            return (Criteria) this;
        }

        public Criteria andShelftimeBetween(Date value1, Date value2) {
            addCriterion("shelftime between", value1, value2, "shelftime");
            return (Criteria) this;
        }

        public Criteria andShelftimeNotBetween(Date value1, Date value2) {
            addCriterion("shelftime not between", value1, value2, "shelftime");
            return (Criteria) this;
        }

        public Criteria andReleasetimeIsNull() {
            addCriterion("releasetime is null");
            return (Criteria) this;
        }

        public Criteria andReleasetimeIsNotNull() {
            addCriterion("releasetime is not null");
            return (Criteria) this;
        }

        public Criteria andReleasetimeEqualTo(Date value) {
            addCriterion("releasetime =", value, "releasetime");
            return (Criteria) this;
        }

        public Criteria andReleasetimeNotEqualTo(Date value) {
            addCriterion("releasetime <>", value, "releasetime");
            return (Criteria) this;
        }

        public Criteria andReleasetimeGreaterThan(Date value) {
            addCriterion("releasetime >", value, "releasetime");
            return (Criteria) this;
        }

        public Criteria andReleasetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("releasetime >=", value, "releasetime");
            return (Criteria) this;
        }

        public Criteria andReleasetimeLessThan(Date value) {
            addCriterion("releasetime <", value, "releasetime");
            return (Criteria) this;
        }

        public Criteria andReleasetimeLessThanOrEqualTo(Date value) {
            addCriterion("releasetime <=", value, "releasetime");
            return (Criteria) this;
        }

        public Criteria andReleasetimeIn(List<Date> values) {
            addCriterion("releasetime in", values, "releasetime");
            return (Criteria) this;
        }

        public Criteria andReleasetimeNotIn(List<Date> values) {
            addCriterion("releasetime not in", values, "releasetime");
            return (Criteria) this;
        }

        public Criteria andReleasetimeBetween(Date value1, Date value2) {
            addCriterion("releasetime between", value1, value2, "releasetime");
            return (Criteria) this;
        }

        public Criteria andReleasetimeNotBetween(Date value1, Date value2) {
            addCriterion("releasetime not between", value1, value2, "releasetime");
            return (Criteria) this;
        }

        public Criteria andBookimageIsNull() {
            addCriterion("bookimage is null");
            return (Criteria) this;
        }

        public Criteria andBookimageIsNotNull() {
            addCriterion("bookimage is not null");
            return (Criteria) this;
        }

        public Criteria andBookimageEqualTo(String value) {
            addCriterion("bookimage =", value, "bookimage");
            return (Criteria) this;
        }

        public Criteria andBookimageNotEqualTo(String value) {
            addCriterion("bookimage <>", value, "bookimage");
            return (Criteria) this;
        }

        public Criteria andBookimageGreaterThan(String value) {
            addCriterion("bookimage >", value, "bookimage");
            return (Criteria) this;
        }

        public Criteria andBookimageGreaterThanOrEqualTo(String value) {
            addCriterion("bookimage >=", value, "bookimage");
            return (Criteria) this;
        }

        public Criteria andBookimageLessThan(String value) {
            addCriterion("bookimage <", value, "bookimage");
            return (Criteria) this;
        }

        public Criteria andBookimageLessThanOrEqualTo(String value) {
            addCriterion("bookimage <=", value, "bookimage");
            return (Criteria) this;
        }

        public Criteria andBookimageLike(String value) {
            addCriterion("bookimage like", value, "bookimage");
            return (Criteria) this;
        }

        public Criteria andBookimageNotLike(String value) {
            addCriterion("bookimage not like", value, "bookimage");
            return (Criteria) this;
        }

        public Criteria andBookimageIn(List<String> values) {
            addCriterion("bookimage in", values, "bookimage");
            return (Criteria) this;
        }

        public Criteria andBookimageNotIn(List<String> values) {
            addCriterion("bookimage not in", values, "bookimage");
            return (Criteria) this;
        }

        public Criteria andBookimageBetween(String value1, String value2) {
            addCriterion("bookimage between", value1, value2, "bookimage");
            return (Criteria) this;
        }

        public Criteria andBookimageNotBetween(String value1, String value2) {
            addCriterion("bookimage not between", value1, value2, "bookimage");
            return (Criteria) this;
        }

        public Criteria andBookstateIsNull() {
            addCriterion("bookstate is null");
            return (Criteria) this;
        }

        public Criteria andBookstateIsNotNull() {
            addCriterion("bookstate is not null");
            return (Criteria) this;
        }

        public Criteria andBookstateEqualTo(Integer value) {
            addCriterion("bookstate =", value, "bookstate");
            return (Criteria) this;
        }

        public Criteria andBookstateNotEqualTo(Integer value) {
            addCriterion("bookstate <>", value, "bookstate");
            return (Criteria) this;
        }

        public Criteria andBookstateGreaterThan(Integer value) {
            addCriterion("bookstate >", value, "bookstate");
            return (Criteria) this;
        }

        public Criteria andBookstateGreaterThanOrEqualTo(Integer value) {
            addCriterion("bookstate >=", value, "bookstate");
            return (Criteria) this;
        }

        public Criteria andBookstateLessThan(Integer value) {
            addCriterion("bookstate <", value, "bookstate");
            return (Criteria) this;
        }

        public Criteria andBookstateLessThanOrEqualTo(Integer value) {
            addCriterion("bookstate <=", value, "bookstate");
            return (Criteria) this;
        }

        public Criteria andBookstateIn(List<Integer> values) {
            addCriterion("bookstate in", values, "bookstate");
            return (Criteria) this;
        }

        public Criteria andBookstateNotIn(List<Integer> values) {
            addCriterion("bookstate not in", values, "bookstate");
            return (Criteria) this;
        }

        public Criteria andBookstateBetween(Integer value1, Integer value2) {
            addCriterion("bookstate between", value1, value2, "bookstate");
            return (Criteria) this;
        }

        public Criteria andBookstateNotBetween(Integer value1, Integer value2) {
            addCriterion("bookstate not between", value1, value2, "bookstate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bookinfo_
     *
     * @mbggenerated do_not_delete_during_merge Fri Dec 29 19:52:50 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bookinfo_
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}