package dao.model;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo_.userID
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo_.username
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo_.password
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo_.email
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo_.phonenumber
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    private Integer phonenumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo_.address
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo_.userID
     *
     * @return the value of userinfo_.userID
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo_.userID
     *
     * @param userid the value for userinfo_.userID
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo_.username
     *
     * @return the value of userinfo_.username
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo_.username
     *
     * @param username the value for userinfo_.username
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo_.password
     *
     * @return the value of userinfo_.password
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo_.password
     *
     * @param password the value for userinfo_.password
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo_.email
     *
     * @return the value of userinfo_.email
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo_.email
     *
     * @param email the value for userinfo_.email
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo_.phonenumber
     *
     * @return the value of userinfo_.phonenumber
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    public Integer getPhonenumber() {
        return phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo_.phonenumber
     *
     * @param phonenumber the value for userinfo_.phonenumber
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    public void setPhonenumber(Integer phonenumber) {
        this.phonenumber = phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo_.address
     *
     * @return the value of userinfo_.address
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo_.address
     *
     * @param address the value for userinfo_.address
     *
     * @mbggenerated Fri Dec 29 19:52:50 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }
}